name: ci
run-name: CI for ${{ github.sha }} on ${{ github.ref_name }}

on:
   workflow_dispatch:
   workflow_call:
   push:
     branches:
     - "main"
     - "release-**"
     - "track/**"
     paths-ignore:
     - "terraform/**"
   pull_request:
     branches:
     - "*"
     paths-ignore:
     - "terraform/**"

jobs:
  linting:
    name: Linting
    uses: canonical/identity-team/.github/workflows/_charm-linting.yaml@83e6e76b28b0db96c133c16bbec121cba34a86db # v1.14.3

  unit-test:
    name: Unit Tests
    uses: canonical/identity-team/.github/workflows/_charm-tests-unit.yaml@83e6e76b28b0db96c133c16bbec121cba34a86db # v1.14.3
    needs:
      - linting

  build:
    name: Build charm
    uses: canonical/identity-team/.github/workflows/_charm-build.yaml@83e6e76b28b0db96c133c16bbec121cba34a86db # v1.14.3
    with:
      use-charmcraftcache: false
    needs:
      - unit-test

  integration-test-k8s:
    name: Integration Tests (microk8s)
    runs-on: [self-hosted, amd64, large, jammy ]
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup operator environment (microk8s)
        uses: charmed-kubernetes/actions-operator@d8217ad61c15f746727a9d41563c13e9b9fe56e3 # main
        with:
          juju-channel: 3.6/stable
          provider: microk8s
          channel: 1.32-strict/stable
          microk8s-addons: "dns hostpath-storage metallb:10.64.140.43-10.64.140.49"

      - name: Get charm info
        id: get-charm-info
        run: |
          echo charm-name=$(cat charmcraft.yaml | yq '.name') >> $GITHUB_OUTPUT

      - name: Set CHARM_PATH envvar
        run: echo "CHARM_PATH=${{ github.workspace }}/${{ needs.build.outputs.charm-paths }}" >> $GITHUB_ENV

      - name: Download charm artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: ${{ needs.build.outputs.artifacts-key }}

      - name: Run integration tests
        run: tox -e build-prerequisites,integration -- --run-k8s --model testing

      - name: Get contexts
        if: failure()
        run: kubectl config view

      - name: Get juju status
        if: failure()
        run: juju status --relations

      - name: Dump logs
        if: failure()
        uses: canonical/charming-actions/dump-logs@9180b22741d2349858e35e1dcc2fe4e11c3ebf2d # main

      - name: Get juju logs for the charm
        if: ${{ failure() }}
        run: juju debug-log --replay --include ${{ steps.get-charm-info.outputs.charm-name }}/0

  integration-test-machine:
    name: Integration Tests (lxd)
    runs-on: [self-hosted, amd64, large, jammy]
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup operator environment (lxd)
        uses: charmed-kubernetes/actions-operator@d8217ad61c15f746727a9d41563c13e9b9fe56e3 # main
        with:
          juju-channel: 3.6/stable
          provider: lxd
          channel: 5.21/stable

      - name: Get charm info
        id: get-charm-info
        run: |
          echo charm-name=$(cat charmcraft.yaml | yq '.name') >> $GITHUB_OUTPUT

      - name: Set CHARM_PATH envvar
        run: echo "CHARM_PATH=${{ github.workspace }}/${{ needs.build.outputs.charm-paths }}" >> $GITHUB_ENV

      - name: Download charm artifact
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: ${{ needs.build.outputs.artifacts-key }}

      - name: Run integration tests
        run: tox -e build-prerequisites,integration -- --run-machine --model testing

      - name: Get juju status
        if: failure()
        run: juju status --relations

      - name: Dump logs
        if: failure()
        uses: canonical/charming-actions/dump-logs@9180b22741d2349858e35e1dcc2fe4e11c3ebf2d # main

      - name: Get juju logs for the charm
        if: ${{ failure() }}
        run: juju debug-log --replay --include ${{ steps.get-charm-info.outputs.charm-name }}/0
