name: On Push

on:
  push:
    branches:
      - main
      - track/**

jobs:
  tests:
    name: Run Tests
    uses: ./.github/workflows/tests.yaml

  publish-charm:
    name: Publish Charm
    needs: tests
    uses: ./.github/workflows/publish.yaml
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
