name: Release Charm Library

on:
  push:
    branches:
      - main
    paths:
      - "lib/charms/ldap_integrator/**"

jobs:
  release-lib:
    name: Release any bumped library
    uses: canonical/identity-team/.github/workflows/charm-libs-release.yaml@74923c8fd716e55207cf19359621902c45b24b52 # v1.8.2
    secrets:
      CHARMCRAFT_CREDENTIALS: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
