name: Release Charm Library

on:
  push:
    branches:
      - main
    paths:
      - "lib/charms/ldap_integrator/**"

jobs:
  release-libs:
    name: Release charm library
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0
      - name: Release charm library
        uses: canonical/charming-actions/release-libraries@main
        with:
          credentials: ${{ secrets.CHARMCRAFT_CREDENTIALS }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
